language: python
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_7b118cfe21b9_key -iv $encrypted_7b118cfe21b9_iv
  -in config.cfg.enc -out config.cfg -d
install: "pip install -r requirements.txt"
script: nosetests
